### ISSUE TITLE
Some clerical errors

### ISSUE THREAD

**Issue by Yuan-Jinghui** [epfml/OptML_course#11]
1、p173,'The following result shows that the duality gap converges as well, essentially at the same rate as the primal error. .',One more full stop
2、Theorem 10.5.  Again, it should be stated that the optimal point is within the defined domain

**Comment by martinjaggi** [comment]
first one is resolved.

second one might be ok from the context already (bounded convex set implies existence of an x*?). 

feel free to reopen the issue if not
