### ISSUE TITLE
cannot find the solution's link

### ISSUE THREAD

**Issue by ChangLee0903** [epfml/OptML_course#8]
Hi,

Cool material to briefly know the big picture of the optimization in ML! It does help me a lot. But I have a question about the Exercises part's description. The link in "Solutions to theory exercises are available here" guides me to the path of "lecture_notes." It seems that the path of the solution link should be the same as the weekly exercises. BTW, could you provide all the exercises' solutions of the note? (not just the selected exercises' solutions)

best regards

**Comment by martinjaggi** [comment]
sorry we're keeping the solutions internal to EPFL for now.

but for the labs, the solutions are still available from last year for example: https://github.com/epfml/OptML_course/tree/30e7c1d2bb6130265d1c3cf3daf0da938030477c/labs

hope this helps

**Comment by ChangLee0903** [comment]
OK, I got it. Thank you.
